Fixed StopIteration, The above exception was the direct cause of
the following exception:
SystemError: <built-in method readinto of _io.FileIO object at
0x6ffffdc1ea0> returned a result with an error set

This happens because now _getline will alsy raise StopIteration
when we already had stopped the iterator/iteration.